### ISSUE TITLE
status 401

### ISSUE THREAD

**Issue by abracadabbra** [svlada/springboot-security-jwt#13]
![image](https://user-images.githubusercontent.com/16486344/34675668-5060fee8-f4c5-11e7-9430-e026818a914c.png)

Hello  
I start your program ,and use "/api/auth/login" to get token. but the responese is 401. i just follow your step on your blog .i don't know why. can you tell me how to do ?

**Comment by svlada** [comment]
It looks like your request is missing some of the HTTP header values. Please check if the following HTTP header values are present in your request:
```
X-Requested-With: XMLHttpRequest
Content-Type: application/json
```

**Comment by abracadabbra** [comment]
Oh , it is my fault . Your answer really fast!! Thank you very much!!! (*^▽^*)

**Comment by svlada** [comment]
@SuperNoobTao No problem, if you have any other questions don't hesitate to ask.
