### ISSUE TITLE
Use of Joda Time

### ISSUE THREAD

**Issue by jsbUSMC** [svlada/springboot-security-jwt#6]
Wonderful writeup, I really appreciate the effort you've put into this example and the blog post. I was wondering though, why are you using Joda Time library instead of the built-in LocalDate and LocalTime classes through the `java.time` package that comes with Java SE 8? I am refactoring some of your classes and integrating them into my project, and Intellij is throwing a fit because I haven't added the dependency to my build.gradle. I don't have a problem doing so, but I was wondering if there is a specific reason for this? Is the Joda Time API easier to use? Thank you very much!

**Comment by svlada** [comment]
@jsbUSMC

Thank you for the kind words.

Good point. I will remove Joda Time dependency and refactor code to use Java 8 time package instead.

Note: Main reason behind using Joda Time is my familiarity with that library.

**Comment by jsbUSMC** [comment]
Thank you once again for your effort with the blog and the code samples
