### ISSUE TITLE
Why populate SecurityContext after JWT auth success?

### ISSUE THREAD

**Issue by prateekmathur1991** [svlada/springboot-security-jwt#7]
Hi Vladimir,

Thanks for the great tutorial. It was immensely helpful in integrating JWT authentication in my new project.

I do have 1 question, though. You populate Spring Security's SecurityContext when JWT authentication flow succeeds, not when the Ajax authentication flow succeeds. But as per my understanding, when a user hits many secured APIs, will that not lead to multiple SecurityContexts being created for the same user? (Afterall, his every request will be with the same token!!)

Can you please explain to me the reason behind this design? I think the SecurityContext should be populated when the Ajax login flow succeeds in the AjaxAwareAuthenticationSuccessHandler.

Thank you.

**Comment by svlada** [comment]
@prateekmathur1991

UserContext is created in both AjaxAuthenticationProvider and JwtAuthenticationProvider.

1. AjaxAuthenticationProvider handles login request
2. JwtAuthenticationProvider handles any api request

Please check the following methods for your reference

com.svlada.security.auth.ajax.AjaxAuthenticationProvider.authenticate(Authentication).
com.svlada.security.auth.jwt.JwtAuthenticationProvider.authenticate(Authentication)

Please bare in mind that this is stateless authentication, so JWT will be extracted from header on each request.

**Comment by prateekmathur1991** [comment]
@svlada Thanks! Clear enough
